'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const M=require('../editor/model.js'),W=require('../editor/workflow.js');
const fixture=()=>JSON.parse(fs.readFileSync(path.join(__dirname,'../examples/workflow-demo.lesson.json'),'utf8'));
function ready(){const d=W.newCourse();d.lessonPackage=fixture();const p=d.lessonPackage;p.sources[0].pages[0].reviewedText=p.sources[0].pages[0].text;W.approve(p,p.items[0].id,true);W.generate(d);return d;}
const raw=W.newCourse();raw.lessonPackage=fixture();assert.throws(()=>W.generate(raw),/核對/);assert.throws(()=>W.approve(raw.lessonPackage,'demo-question',true),/原頁核對/);
let d=ready();assert.equal(W.releaseIssues(d).length,0);
const body=()=>d.slides[0].elements.find(e=>e.role==='body');
body().x=40;body().w=880;d.slides[0].elements.reverse();W.reconcile(d);
assert.ok(W.isReviewed(d.lessonPackage,d.lessonPackage.items[0]),'layout must not invalidate content review');
W.generate(d);assert.equal(body().x,40);assert.equal(body().w,880);assert.equal(d.slides[0].elements[0].role,'body','z-order survives regeneration');
body().backText='我今天过得很好，因为我见到了朋友。';W.reconcile(d);
assert.equal(d.lessonPackage.items[0].blocks.find(b=>b.role==='body').backText,body().backText);
assert.ok(!W.isReviewed(d.lessonPackage,d.lessonPackage.items[0]));assert.throws(()=>W.generate(d),/核對/);
W.approve(d.lessonPackage,'demo-question',true);W.generate(d);assert.equal(body().x,40);assert.ok(body().backText.includes('朋友'));
d.lessonPackage.sources[0].pages[0].text+='教材更正';assert.ok(!W.isReviewed(d.lessonPackage,d.lessonPackage.items[0]));assert.throws(()=>W.generate(d),/原頁核對/);
d=ready();d.lessonPackage.items[0].blocks.find(b=>b.role==='body').backText='';assert.throws(()=>W.approve(d.lessonPackage,'demo-question',true),/答案/);
d=ready();d.lessonPackage.items[0].exerciseType='vocabulary-drill';assert.throws(()=>W.approve(d.lessonPackage,'demo-question',true),/KN2/);d.lessonPackage.items[0].exception='教師指定本題為複習例外';W.approve(d.lessonPackage,'demo-question',true);
d=ready();d.layoutOverrides['demo-question']={elements:{'demo-body':{text:'INJECTED',backText:'INJECTED',x:40,w:880}}};W.generate(d);assert.notEqual(body().text,'INJECTED');assert.equal(body().x,40);
const safe=JSON.stringify(W.studentView(d));for(const forbidden of ['lessonPackage','reviewedText','fingerprint','只示範教材核對'])assert.ok(!safe.includes(forbidden));
const saved=M.validate(JSON.parse(JSON.stringify(d)));W.generate(saved);assert.equal(saved.slides[0].elements.find(e=>e.role==='body').x,40);
const legacy=M.blank();W.migrate(legacy);assert.ok(W.releaseIssues(legacy).length);assert.equal(legacy.lessonPackage.items.length,1);
const duplicated=fixture();duplicated.items.push(M.clone(duplicated.items[0]));assert.throws(()=>W.validatePackage(duplicated),/ID/);
d=ready();body().text='Untracked replacement';d.workflow.projection=JSON.stringify(d.slides);assert.ok(W.releaseIssues(d).some(e=>e.message.includes('不一致')));
d=ready();assert.ok(W.contentMatches(d));d.lessonPackage.items[0].blocks.find(b=>b.role==='body').backText='我今天很愉快。';
assert.ok(!W.contentMatches(d),'pending database edits must lock the old canvas');W.reconcile(d);
assert.equal(d.lessonPackage.items[0].blocks.find(b=>b.role==='body').backText,'我今天很愉快。');
W.approve(d.lessonPackage,'demo-question',true);W.generate(d);assert.ok(W.contentMatches(d));
console.log('Course workflow: source gate, answer rules, review invalidation, writeback, layout preservation, reload, migration and student export passed');
